"""change_schedule_time

Revision ID: 1e41fb92622d
Revises: 9f68ac13faf3
Create Date: 2026-07-31 22:36:46.469600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e41fb92622d'
down_revision: Union[str, None] = '9f68ac13faf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'departure_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_comment='Departure date and time',
               existing_nullable=False,
               postgresql_using='departure_time::time with time zone')
    op.alter_column('schedules', 'arrival_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_comment='Arrival date and time',
               existing_nullable=False,
               postgresql_using='arrival_time::time with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'arrival_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Arrival date and time',
               existing_nullable=False)
    op.alter_column('schedules', 'departure_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Departure date and time',
               existing_nullable=False)
    # ### end Alembic commands ###
