"""route_table_add

Revision ID: 1f3dec66e343
Revises: 4d73dc5a048d
Create Date: 2026-07-24 23:57:59.939287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3dec66e343'
down_revision: Union[str, None] = '4d73dc5a048d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Route name (e.g., Yangon - Mandalay)'),
    sa.Column('origin', sa.String(length=255), nullable=False, comment='Origin City'),
    sa.Column('destination', sa.String(length=255), nullable=False, comment='Destination City'),
    sa.Column('distance', sa.Float(), nullable=True, comment='Distance in kilometers'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Estimated duration in minutes'),
    sa.Column('base_price', sa.Float(), nullable=False, comment='Base price for this route'),
    sa.Column('description', sa.Text(), nullable=True, comment='Company description'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=True)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_origin'), 'routes', ['origin'], unique=False)
    op.create_index('ix_routes_origin_destination', 'routes', ['origin', 'destination'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routes_origin_destination', table_name='routes')
    op.drop_index(op.f('ix_routes_origin'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
