"""add_bus_images_table

Revision ID: 323d93cf08dd
Revises: 03d38fa24457
Create Date: 2026-08-08 23:27:50.992710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323d93cf08dd'
down_revision: Union[str, None] = '03d38fa24457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_images',
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Image URL (Cloudinary or local)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Order of the image for display purposes'),
    sa.Column('bus_id', sa.UUID(), nullable=False, comment='Bus this image belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_images_bus_id'), 'bus_images', ['bus_id'], unique=False)
    op.create_index(op.f('ix_bus_images_id'), 'bus_images', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_images_id'), table_name='bus_images')
    op.drop_index(op.f('ix_bus_images_bus_id'), table_name='bus_images')
    op.drop_table('bus_images')
    # ### end Alembic commands ###
