"""add_booking_and_promotion

Revision ID: 465cf7d0fbde
Revises: 34e8ed628fc8
Create Date: 2026-08-09 22:01:15.656828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465cf7d0fbde'
down_revision: Union[str, None] = '34e8ed628fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_number', sa.String(length=50), nullable=False, comment='Unique booking reference'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='Total amount before discount'),
    sa.Column('discount_amount', sa.Float(), nullable=False, comment='Discount applied'),
    sa.Column('final_amount', sa.Float(), nullable=False, comment='Final amount after discount'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False, comment='Booking status'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who made the booking'),
    sa.Column('schedule_id', sa.UUID(), nullable=False, comment='Schedule ID'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=True)
    op.create_index(op.f('ix_bookings_schedule_id'), 'bookings', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.add_column('promotion_usages', sa.Column('booking_id', sa.UUID(), nullable=True, comment='Booking ID (if applicable)'))
    op.create_index(op.f('ix_promotion_usages_booking_id'), 'promotion_usages', ['booking_id'], unique=False)
    op.create_foreign_key(None, 'promotion_usages', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotion_usages', type_='foreignkey')
    op.drop_index(op.f('ix_promotion_usages_booking_id'), table_name='promotion_usages')
    op.drop_column('promotion_usages', 'booking_id')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_schedule_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
