"""change festival

Revision ID: 4892b765308e
Revises: 465cf7d0fbde
Create Date: 2026-08-11 00:05:48.095154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4892b765308e'
down_revision: Union[str, None] = '465cf7d0fbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_index('ix_payments_invoice_no', table_name='payments')
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_booking_seats_booking_id', table_name='booking_seats')
    op.drop_index('ix_booking_seats_id', table_name='booking_seats')
    op.drop_index('ix_booking_seats_schedule_id', table_name='booking_seats')
    op.drop_index('ix_booking_seats_seat_id', table_name='booking_seats')
    op.drop_table('booking_seats')
    op.alter_column('schedules', 'local_festival_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_comment='Festival price for locals',
               existing_server_default=sa.text('0.00'))
    op.alter_column('schedules', 'foreigner_festival_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_comment='Festival price for foreigners',
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'foreigner_festival_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_comment='Festival price for foreigners',
               existing_server_default=sa.text('0.00'))
    op.alter_column('schedules', 'local_festival_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_comment='Festival price for locals',
               existing_server_default=sa.text('0.00'))
    op.create_table('booking_seats',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False, comment='Booking ID'),
    sa.Column('seat_id', sa.UUID(), autoincrement=False, nullable=False, comment='Seat ID'),
    sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False, comment='Schedule ID this seat is booked for'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_seats_booking_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='booking_seats_schedule_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name='booking_seats_seat_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='booking_seats_pkey'),
    sa.UniqueConstraint('seat_id', 'schedule_id', name='unique_seat_per_schedule')
    )
    op.create_index('ix_booking_seats_seat_id', 'booking_seats', ['seat_id'], unique=False)
    op.create_index('ix_booking_seats_schedule_id', 'booking_seats', ['schedule_id'], unique=False)
    op.create_index('ix_booking_seats_id', 'booking_seats', ['id'], unique=True)
    op.create_index('ix_booking_seats_booking_id', 'booking_seats', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False, comment='Booking ID'),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Payment amount in MMK'),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='Currency code'),
    sa.Column('payment_method', postgresql.ENUM('KBZPAY', 'WAVE_MONEY', 'CB_PAY', 'CARD', 'QR', 'UNKNOWN', name='paymentmethod'), autoincrement=False, nullable=True, comment='Payment method used'),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), autoincrement=False, nullable=False, comment='Payment status'),
    sa.Column('invoice_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='2C2P invoice number (merchant order number)'),
    sa.Column('payment_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='2C2P payment token'),
    sa.Column('web_payment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='2C2P hosted payment page URL'),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Gateway transaction ID'),
    sa.Column('reference_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Gateway reference number'),
    sa.Column('approval_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Approval code from gateway'),
    sa.Column('gateway_response', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='Raw response from gateway'),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Error message if payment failed'),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When payment was completed'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When payment expires'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='payments_booking_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('ix_payments_invoice_no', 'payments', ['invoice_no'], unique=True)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=True)
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    # ### end Alembic commands ###
