"""add_buses_table

Revision ID: 4d73dc5a048d
Revises: 9824102e748c
Create Date: 2026-07-23 01:35:33.247301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d73dc5a048d'
down_revision: Union[str, None] = '9824102e748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('bus_number', sa.String(length=50), nullable=False, comment='Bus number (e.g., B-001)'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='Total Number of Seats in the Bus'),
    sa.Column('bus_type', sa.Enum('AC', 'NonAC', 'VIP', 'Express', name='bustype'), nullable=False, comment='Type of the Bus (e.g., AC, Non-AC, VIP, Express)'),
    sa.Column('license_plate', sa.String(length=20), nullable=False, comment='Vehicle license plate'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the company is active'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company this bus belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_bus_number'), 'buses', ['bus_number'], unique=True)
    op.create_index(op.f('ix_buses_company_id'), 'buses', ['company_id'], unique=False)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=True)
    op.create_index(op.f('ix_buses_license_plate'), 'buses', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buses_license_plate'), table_name='buses')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_company_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
