"""add_seat_layouts_table

Revision ID: 5108e54e9ce5
Revises: 861a91b26391
Create Date: 2026-07-26 22:31:54.059585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5108e54e9ce5'
down_revision: Union[str, None] = '861a91b26391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
