"""create_bus_feature_table

Revision ID: 7845909131be
Revises: 2dd956c767c6
Create Date: 2026-08-08 22:05:03.784279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7845909131be'
down_revision: Union[str, None] = '2dd956c767c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'bus_features',
        existing_comment='Many-to-many relationship between buses and features',
        schema=None
    )
    op.alter_column('features', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='Feature name',
               existing_nullable=False)
    op.alter_column('features', 'icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='Feature icon (optional)',
               existing_nullable=True)
    op.alter_column('features', 'description',
               existing_type=sa.TEXT(),
               comment='Feature description',
               existing_nullable=True)
    op.alter_column('features', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indicates if the feature is active',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('features', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates if the feature is active',
               existing_nullable=False)
    op.alter_column('features', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Feature description',
               existing_nullable=True)
    op.alter_column('features', 'icon',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Feature icon (optional)',
               existing_nullable=True)
    op.alter_column('features', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Feature name',
               existing_nullable=False)
    op.create_table_comment(
        'bus_features',
        'Many-to-many relationship between buses and features',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
