"""add_seat_layout_table

Revision ID: 861a91b26391
Revises: e39de1d32b12
Create Date: 2026-07-26 21:39:21.670942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861a91b26391'
down_revision: Union[str, None] = 'e39de1d32b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_layouts',
    sa.Column('bus_id', sa.UUID(), nullable=False, comment='Bus ID'),
    sa.Column('rows', sa.Integer(), nullable=False, comment='Total rows'),
    sa.Column('columns', sa.Integer(), nullable=False, comment='Total columns per row (seats per row)'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Advanced layout config (e.g., aisle positions, skipped seats)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_layouts_bus_id'), 'seat_layouts', ['bus_id'], unique=True)
    op.create_index(op.f('ix_seat_layouts_id'), 'seat_layouts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_layouts_id'), table_name='seat_layouts')
    op.drop_index(op.f('ix_seat_layouts_bus_id'), table_name='seat_layouts')
    op.drop_table('seat_layouts')
    # ### end Alembic commands ###
