"""add_bus_companies

Revision ID: 9824102e748c
Revises: db77df93f343
Create Date: 2026-07-20 00:51:57.016018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9824102e748c'
down_revision: Union[str, None] = 'db77df93f343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_companies',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Company name (e.g., JJ Express)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Company description'),
    sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Contact email address'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Contact phone number'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Company address'),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment="URL to the company's logo image"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the company is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_companies_id'), 'bus_companies', ['id'], unique=True)
    op.create_index(op.f('ix_bus_companies_name'), 'bus_companies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_companies_name'), table_name='bus_companies')
    op.drop_index(op.f('ix_bus_companies_id'), table_name='bus_companies')
    op.drop_table('bus_companies')
    # ### end Alembic commands ###
