"""add_dynamic_pricing_and_booking_window

Revision ID: 9f68ac13faf3
Revises: 8488944abe8c
Create Date: 2026-07-31 19:06:00.006576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f68ac13faf3'
down_revision: Union[str, None] = '8488944abe8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint and index on schedules first before dropping festivals table
    op.drop_index('ix_schedules_festival_id', table_name='schedules')
    op.drop_constraint('schedules_festival_id_fkey', 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'festival_id')
    op.drop_index('ix_festivals_id', table_name='festivals')
    op.drop_table('festivals')
    op.add_column('schedules', sa.Column('festival_start_date', sa.DateTime(timezone=True), nullable=True, comment='Festival period start'))
    op.add_column('schedules', sa.Column('festival_end_date', sa.DateTime(timezone=True), nullable=True, comment='Festival period end'))
    op.alter_column('schedules', 'departure_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(timezone=True),
               comment='Departure date and time',
               existing_nullable=False,
               postgresql_using="(date '2024-01-01' + departure_time)::timestamp with time zone")
    op.alter_column('schedules', 'arrival_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(timezone=True),
               comment='Arrival date and time',
               existing_nullable=False,
               postgresql_using="(date '2024-01-01' + arrival_time)::timestamp with time zone")
    op.alter_column('schedules', 'local_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='Price for local citizens',
               existing_nullable=False)
    op.alter_column('schedules', 'foreigner_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               comment='Price for foreigners citizens',
               existing_comment='Price for foreigners',
               existing_nullable=False)
    op.alter_column('schedules', 'local_festival_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False,
               comment='Festival price for locals',
               existing_comment='Price for locals during festival season')
    op.alter_column('schedules', 'foreigner_festival_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False,
               comment='Festival price for foreigners',
               existing_comment='Price for foreigners during festival season')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('festival_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('schedules_festival_id_fkey', 'schedules', 'festivals', ['festival_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_schedules_festival_id', 'schedules', ['festival_id'], unique=False)
    op.alter_column('schedules', 'foreigner_festival_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Price for foreigners during festival season',
               existing_comment='Festival price for foreigners')
    op.alter_column('schedules', 'local_festival_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Price for locals during festival season',
               existing_comment='Festival price for locals')
    op.alter_column('schedules', 'foreigner_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Price for foreigners',
               existing_comment='Price for foreigners citizens',
               existing_nullable=False)
    op.alter_column('schedules', 'local_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Price for local citizens',
               existing_nullable=False)
    op.alter_column('schedules', 'arrival_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(),
               comment=None,
               existing_comment='Arrival date and time',
               existing_nullable=False)
    op.alter_column('schedules', 'departure_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(),
               comment=None,
               existing_comment='Departure date and time',
               existing_nullable=False)
    op.drop_column('schedules', 'festival_end_date')
    op.drop_column('schedules', 'festival_start_date')
    op.create_table('festivals',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='festivals_pkey')
    )
    op.create_index('ix_festivals_id', 'festivals', ['id'], unique=True)
    # ### end Alembic commands ###
