"""add_bus_companies

Revision ID: dc81b41d307d
Revises: 0ebbcb00ae6a
Create Date: 2026-07-19 01:05:46.256085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc81b41d307d'
down_revision: Union[str, None] = '0ebbcb00ae6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
