"""add_seat_table

Revision ID: e39de1d32b12
Revises: 94099f46183f
Create Date: 2026-07-26 20:23:45.445295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39de1d32b12'
down_revision: Union[str, None] = '94099f46183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('seat_number', sa.String(length=50), nullable=False, comment='Seat number (e.g., A-01)'),
    sa.Column('row', sa.Integer(), nullable=True, comment='Row number (e.g., 1)'),
    sa.Column('column', sa.String(length=10), nullable=True, comment='Column letter (e.g., A)'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Indicates if the seat is available'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is this seat active?'),
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_id', 'seat_number', name='unique_seat_number_per_bus')
    )
    op.create_index(op.f('ix_seats_bus_id'), 'seats', ['bus_id'], unique=False)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_bus_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
